name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: dynamic-labs/sdk/.github/actions/setup-node@main

      - run: pnpm install --frozen-lockfile
      - run: pnpm exec nx affected -t lint test build
